USE LuaTubeDb;

INSERT INTO Tag(Id, Name) VALUES
(1, 'Maquiagem');

INSERT INTO Video VALUES
( 1, 'MAQUIAGEM PARA INICIANTES:TUDO O QUE VOCÊ PRECISA SABER PARA *SE MAQUIAR* | PASSO A PASSO COMPLETO!', 'Se Inscreva para Mais', '2022-12-09', 9, 15, '\\img\\1.jpg', '.'),
( 1, 'MAKE ELEGANTE PRA FESTAS E EVENTOS CHIQUES | MAQUIAGEM PRA TE DEIXAR LINDA EM QUALQUER FESTA!!!', 'Make para Festas', '2023-04-16', 13, 15, '\\img\\2.jpg','.'),
( 1, 'COMO FAZER UMA MAKE SIMPLES E ELEGANTE!! APRENDA DE *FORMA FÁCIL*', 'Make Simples', '2023-06-05', 17, 15, '\\img\\3.jpg','.'),
( 1, 'MAKE DE 300 MIL 😱 VOCÊS PRECISAM APRENDER ESSA MAKE | MAQUIAGEM PROFISSIONAL', 'Make Profissional', '2023-07-26', 25, 15, '\\img\\4.jpg','.');